spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5435/resignation_db}
    username: ${DATABASE_USERNAME:resignation_service_db_tech_username}
    password: ${DATABASE_PASSWORD:pass}
server:
  port: ${SERVER_PORT:0}
accounting:
  base:
    url: ${ACCOUNTING_BASE_URL:http://accounting-service}
security:
  base:
    url: ${SECURITY_BASE_URL:http://security-service}
profiler:
  base:
    url: ${PROFILER_BASE_URL:http://profiler-service}